it_company_task_manager/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from task_manager.views import LoginView

urlpatterns = [
	path("admin/", admin.site.urls),
	path("", include("task_manager.urls", "task_manager")),
	path("accounts/login/", LoginView.as_view(), name="login"),
	path("accounts/", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
	from django.conf.urls.static import static

	from debug_toolbar.toolbar import debug_toolbar_urls

	urlpatterns += static(
		settings.STATIC_URL, document_root=settings.STATIC_ROOT
	)

	urlpatterns += debug_toolbar_urls()

task_manager/urls.py
from django.urls import path

from task_manager.views import (
	index,
	WorkerListView,
	WorkerCreateView,
	WorkerDetailView,
	WorkerUpdateView,
	WorkerDeleteView,
	TaskListView,
	TaskCreateView,
	TaskDetailView,
	TaskUpdateView,
	TaskDeleteView,
)

urlpatterns = [
	path("", index, name="index"),
	path("workers/", WorkerListView.as_view(), name="worker_list"),
	path("workers/create/", WorkerCreateView.as_view(), name="worker_create"),
	path(
		"workers/<int:pk>/", WorkerDetailView.as_view(), name="worker_detail"
	),
	path(
		"workers/update/<int:pk>/",
		WorkerUpdateView.as_view(),
		name="worker_update"
	),
	path(
		"workers/delete/<int:pk>/",
		WorkerDeleteView.as_view(),
		name="worker_delete"
	),
	path("tasks/", TaskListView.as_view(), name="task_list"),
	path("tasks/create/", TaskCreateView.as_view(), name="task_create"),
	path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task_detail"),
	path(
		"tasks/update/<int:pk>/", TaskUpdateView.as_view(), name="task_update"
	),
	path(
		"tasks/delete/<int:pk>/", TaskDeleteView.as_view(), name="task_delete"
	),
]

app_name = "task_manager"

templates/includes/deadline_overdue_indicator.html
class="{% if not task.is_completed and task.deadline < today %}
	text-danger text-gradient fw-bolder
{% endif %}"

templates/includes/footer_background.html
{% load static %}

<footer class="footer pt-5 mt-5">
	<hr class="horizontal dark mb-5">
	<div class="container">
		<div class=" row">
			<div class="col-md-3 mb-4 ms-auto">
				<div>
					<h6 class="text-gradient text-primary font-weight-bolder">Task
						Manager Pro
					</h6>
				</div>
				<div>
					<h6 class="mt-3 mb-2 opacity-8">Social</h6>
					<ul class="d-flex flex-row ms-n3 nav">
						<li class="nav-item">
							<a class="nav-link pe-1"
								 href="#">
								<i class="fab fa-facebook text-lg opacity-8"></i>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link pe-1"
								 href="#">
								<i class="fab fa-twitter text-lg opacity-8"></i>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link pe-1"
								 href="#">
								<i class="fab fa-dribbble text-lg opacity-8"></i>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link pe-1"
								 href="#">
								<i class="fab fa-github text-lg opacity-8"></i>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link pe-1"
								 href="#">
								<i class="fab fa-youtube text-lg opacity-8"></i>
							</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="col-md-2 col-sm-6 col-6 mb-4">
				<div>
					<h6 class="text-gradient text-primary text-sm">Company</h6>
					<ul class="flex-column ms-n3 nav">
						<li class="nav-item">
							<a class="nav-link"
								 href="#">
								About Us
							</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="col-md-2 col-sm-6 col-6 mb-4">
				<div>
					<h6 class="text-gradient text-primary text-sm">Resources</h6>
					<ul class="flex-column ms-n3 nav">
						<li class="nav-item">
							<a class="nav-link"
								 href="#">
								Illustrations
							</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="col-md-2 col-sm-6 col-6 mb-4">
				<div>
					<h6 class="text-gradient text-primary text-sm">Help & Support</h6>
					<ul class="flex-column ms-n3 nav">
						<li class="nav-item">
							<a class="nav-link"
								 href="#">
								Contact Us
							</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="col-md-2 col-sm-6 col-6 mb-4 me-auto">
				<div>
					<h6 class="text-gradient text-primary text-sm">Legal</h6>
					<ul class="flex-column ms-n3 nav">
						<li class="nav-item">
							<a class="nav-link"
								 href="#">
								Terms &amp; Conditions
							</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="col-12">
				<div class="text-center">
					<p class="my-4 text-sm">
						&copy;
						Creative team
						- Coded by AppSeed.
					</p>
				</div>
			</div>
		</div>
	</div>
</footer>

templates/includes/footer_signin.html
<footer class="footer position-absolute bottom-2 py-2 w-100">
	<div class="container">
		<div class="row align-items-center justify-content-lg-between">
			<div class="col-12 col-md-6 my-auto">
				<div class="copyright text-center text-sm text-white text-lg-start">
					&copy;
					<a class="font-weight-bold text-white"
						 href="#">Creative team
					</a>
					- Coded by AppSeed.
				</div>
			</div>
			<div class="col-12 col-md-6">
				<ul class="nav nav-footer justify-content-center justify-content-lg-end">
					<li class="nav-item">
						<a href="#"
							 class="nav-link text-white">Creative team
						</a>
					</li>
					<li class="nav-item">
						<a href="#"
							 class="nav-link text-white">About Us
						</a>
					</li>
					<li class="nav-item">
						<a href="#"
							 class="nav-link text-white">Blog
						</a>
					</li>
					<li class="nav-item">
						<a href="#"
							 class="nav-link pe-0 text-white">License
						</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</footer>

templates/includes/form_banner.html
{% load static %}
<div class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 end-0 text-center justify-content-center flex-column">
	<div class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center">
		<img src="{% static 'img/shapes/pattern-lines.svg' %}"
				 alt="pattern-lines"
				 class="position-absolute opacity-4 start-0">
		<div class="position-relative">
			<img class="max-width-500 w-100 position-relative z-index-2"
					 src="{% static 'img/illustrations/chat.png' %}"
					 alt="">
		</div>
		<h4 class="mt-5 text-white font-weight-bolder">
			&quot;Attention is the new currency&quot;
		</h4>
		<p class="text-white">
			The more effortless the writing looks, the more effort the writer actually put into the process.
		</p>
	</div>
</div>

templates/includes/navigation.html
{% load static %}

<div class="container position-sticky z-index-sticky top-0">
	<div class="row">
		<div class="col-12">
			<nav
				class="navbar navbar-expand-lg blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
				<div class="container-fluid px-0">
					<a
						class="navbar-brand font-weight-bolder ms-sm-2 mb-0 bg-gradient-primary btn btn-rounded"
						href="{% url "task_manager:index" %}"
						rel="tooltip"> Task Manager
					</a>

					<button
						class="navbar-toggler shadow-none ms-2"
						type="button"
						data-bs-toggle="collapse"
						data-bs-target="#navigation"
						aria-controls="navigation"
						aria-expanded="false"
						aria-label="Toggle navigation">
						<span class="navbar-toggler-icon mt-2">
							<span class="navbar-toggler-bar bar1"></span>
							<span class="navbar-toggler-bar bar2"></span>
							<span class="navbar-toggler-bar bar3"></span>
						</span>
					</button>
					<div
						class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100"
						id="navigation">
						<ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">

							<!-- Users List Icon -->
							<li class="nav-item">
								<a
									class="nav-link nav-link-icon"
									href="{% url "task_manager:worker_list" %}"
									data-bs-toggle="tooltip"
									data-bs-placement="bottom"
									title="Workers list">
									<span class="text-gradient text-primary">
										<i class="fas fa-user-friends me-1 fa-lg"></i>
									</span>
									<span class="text-sm">Workers</span>
								</a>
							</li>

							<!-- Task Dropdown -->
							<li class="nav-item dropdown dropdown-hover mx-2">
								<div
									class="nav-link ps-2 d-flex align-items-center cursor-pointer"
									id="dropdownMenuBlocks"
									data-bs-toggle="dropdown"
									title="Task options">
									<span class="text-gradient text-primary">
										<i class="fas fa-tasks fa-lg me-2"></i>
									</span>
									Task <img
									src="{% static 'img/down-arrow-white.svg' %}"
									alt="down-arrow"
									class="arrow ms-1"/></div>
								<ul
									class="dropdown-menu p-3 border-radius-lg mt-0 mt-lg-3 overflow-hidden"
									aria-labelledby="dropdownMenuBlocks">
									<li class="dropdown-subitem">
										<a
											class="dropdown-item py-2 ps-3 border-radius-md"
											href="{% url "task_manager:task_list" %}">
											<div class="d-flex align-items-center">
												<div class="icon h-10 me-3 d-flex">
													<i
														class="ni ni-single-copy-04 text-gradient text-primary"></i>
												</div>
												<div
													class="w-100 d-flex align-items-center justify-content-between">
													<p class="text-dark p-0 m-0">
														List
													</p>
												</div>
											</div>
										</a>
									</li>
									<li class="dropdown-subitem">
										<a
											class="dropdown-item py-2 ps-3 border-radius-md"
											href="{% url "task_manager:task_create" %}">
											<div class="d-flex align-items-center">
												<div class="icon h-10 me-3 d-flex">
													<i
														class="ni ni-badge text-gradient text-primary"></i>
												</div>
												<div
													class="w-100 d-flex align-items-center justify-content-between">
													<p class="text-dark p-0 m-0">
														Create
													</p>
												</div>
											</div>
										</a>
									</li>
								</ul>
							</li>

							{% if request.user.is_authenticated %}
								<!-- User Detail Icon -->
								<li class="nav-item ms-lg-auto">
									<a class="nav-link nav-link-icon"
										 href="{% url "task_manager:worker_detail" request.user.pk %}"
										 data-bs-toggle="tooltip"
										 data-bs-placement="bottom"
										 title="My page">
										<span class="text-gradient text-primary">
											<i class="far fa-user fa-lg"></i>
										</span>
									</a>
								</li>
								<!-- Logout Button -->
								<li class="nav-item ms-2 d-flex align-items-center">
									<form action="{% url "logout" %}"
												method="post">
										{% csrf_token %}
										<button class="bg-transparent border-0 p-lg-1"
														data-bs-toggle="tooltip"
														data-bs-placement="bottom"
														title="Logout">
											<span class="text-gradient text-primary">
												<i class="fa fa-sign-out"></i>
											</span>
										</button>
									</form>
								</li>
							{% else %}
								<!-- Login Button -->
								<li class="nav-item ms-lg-auto ms-lg-2">
									<a class="nav-link nav-link-icon"
										 href="{% url "login" %}"
										 data-bs-toggle="tooltip"
										 data-bs-placement="bottom"
										 title="Login">
										<span class="text-gradient text-primary">
											<i class="fa fa-sign-in fa-lg"></i>
										</span>
									</a>
								</li>
							{% endif %}
						</ul>
					</div>
				</div>
			</nav>
		</div>
	</div>
</div>

templates/includes/pagination.html
<nav aria-label="Page navigation">
	<ul
		class="pagination justify-content-center align-items-center">
		{% if is_paginated %}
			{% if page_obj.has_previous %}
				<li class="page-item">
					<a
						href="{% querystring page=page_obj.previous_page_number %}"
						class="page-link"
						aria-label="Previous">
						<span
							aria-hidden="true">&laquo;
						</span>
					</a>
				</li>
			{% endif %}

			<!-- Page Info -->
			<li class="page-item">
				<div class="badge bg-gradient-primary rounded-3 p-3 m-2">
					{{ page_obj.number }} of {{ paginator.num_pages }}
				</div>
			</li>

			<!-- Next Button -->
			{% if page_obj.has_next %}
				<li class="page-item">
					<a
						href="{% querystring page=page_obj.next_page_number %}"
						class="page-link"
						aria-label="Next">
						<span
							aria-hidden="true">&raquo;
						</span>
					</a>
				</li>
			{% endif %}
		{% endif %}
	</ul>
</nav>

templates/includes/radio_field.html
{# Required variables: field (form field object), initial (initial value), field_validated_value (validated user input) #}

<div class="text-primary mb-2">
	{{ field.label }}
</div>

{% for value, label in field.field.choices %}
	<div class="form-check">
		<input
			class="form-check-input"
			type="radio"
			id="id_{{ field.name }}_{{ value }}"
			name="{{ field.name }}"
			value="{{ value }}"
			{% if initial == value or field_validated_value == value|stringformat:"s" %}
			checked
			{% endif %}>
		<label class="form-check-label"
					 for="id_{{ field.name }}_{{ value }}">
			{{ label }}
		</label>
	</div>
{% endfor %}

<div class="text-danger">
	{{ field.errors }}
</div>

templates/includes/scripts.html
{% load static %}

<!-- Core JS Files -->
<script src="{% static 'js/core/popper.min.js' %}"
				type="text/javascript"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}"
				type="text/javascript"></script>
<script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>

<!-- Plugins -->
<script src="{% static 'js/plugins/parallax.min.js' %}"></script>
<script src="{% static 'js/plugins/choices.min.js' %}"></script>
<script src="{% static 'js/plugins/countup.min.js' %}"></script>
<script src="{% static 'js/plugins/prism.min.js' %}"></script>
<script src="{% static 'js/plugins/flatpickr.min.js' %}"></script>
<script src="{% static 'js/plugins/moment.min.js' %}"></script>
<script src="{% static 'js/plugins/rellax.min.js' %}"></script>
<script src="{% static 'js/plugins/tilt.min.js' %}"></script>
<script src="{% static 'js/plugins/typedjs.js' %}"></script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>

<script src="{% static 'js/soft-design-system.min.js' %}"
				type="text/javascript"></script>

templates/includes/search.html
<!-- Search -->
<div class="row text-center py-2 mt-3">
	<div class="col-6 mx-auto">
		<div class="input-group mb-5">
			<form action=""
						method="get"
						class="w-80 m-auto d-flex align-items-center">
				{{ search_form.query }}
				<button type="submit"
								class="btn btn-primary m-0 ms-3"
								data-bs-toggle="tooltip"
								data-bs-placement="top"
								title="Search">
					<i class="fa-solid fa-magnifying-glass"></i>
				</button>
				{% if request.GET.query %}
					<a href="{% querystring query='' page=None %}"
						 data-bs-toggle="tooltip"
						 data-bs-placement="top"
						 title="Reset"
						 class="btn btn-danger m-0 ms-3">
						<i class="fa-solid fa-xmark"></i>
					</a>
				{% endif %}
			</form>
		</div>
	</div>
</div>

templates/includes/svg_waves.html
<div class="position-absolute w-100 z-index-1 bottom-0">
	<svg
		class="waves"
		xmlns="http://www.w3.org/2000/svg"
		xmlns:xlink="http://www.w3.org/1999/xlink"
		viewBox="0 24 150 40"
		preserveAspectRatio="none"
		shape-rendering="auto">
		<defs>
			<path
				id="gentle-wave"
				d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"></path>
		</defs>
		<g class="moving-waves">
			<use
				xlink:href="#gentle-wave"
				x="48"
				y="-1"
				fill="rgba(255,255,255,0.40)"></use>
			<use
				xlink:href="#gentle-wave"
				x="48"
				y="3"
				fill="rgba(255,255,255,0.35)"></use>
			<use
				xlink:href="#gentle-wave"
				x="48"
				y="5"
				fill="rgba(255,255,255,0.25)"></use>
			<use
				xlink:href="#gentle-wave"
				x="48"
				y="8"
				fill="rgba(255,255,255,0.20)"></use>
			<use
				xlink:href="#gentle-wave"
				x="48"
				y="13"
				fill="rgba(255,255,255,0.15)"></use>
			<use
				xlink:href="#gentle-wave"
				x="48"
				y="16"
				fill="rgba(255,255,255,0.95)"></use>
		</g>
	</svg>
</div>

templates/includes/task_card.html
<div class="col-md-6">
	<div class="card shadow-sm">
		<div class="card-header bg-gradient-{{ task.is_completed|yesno:"success,faded-dark" }} text-white d-flex align-items-center justify-content-between border border-1 ">
			<h5 class="card-title text-uppercase mb-0">{{ task }}</h5>
			{% if user.is_superuser or user.pk|stringformat:"s" in request.path %}
				<a href="{% url "task_manager:task_update" task.pk %}?next={{ request.path }}">
					<i
						class="fas fa-edit me-2 border border-1 p-3 card"
						aria-hidden="true"></i>
				</a>
			{% endif %}
		</div>
		<div class="card-body">
			<div class="container border-start border-primary border-2">
				<p>
					<strong>Type:</strong>
					{{ task.task_type }}</p>
				<p>
					{% include "includes/task_priority_indicator.html" %}
				</p>
				<p {% include "includes/deadline_overdue_indicator.html" %}>
					<strong>Deadline:</strong>
					<i>{{ task.deadline }}</i>
				</p>
			</div>
			<div class="text-center mt-4">
				<a
					href="{% url "task_manager:task_detail" task.pk %}"
					class="btn btn-outline-primary btn-sm">
					View Task Details
				</a>
			</div>
		</div>
	</div>
</div>

templates/includes/task_priority_indicator.html
{% if task.priority == 4 %}
	<span class="badge bg-gradient-danger">Urgent</span>
{% elif task.priority == 3 %}
	<span class="badge bg-gradient-warning">High</span>
{% elif task.priority == 2 %}
	<span class="badge bg-gradient-success">Medium</span>
{% elif task.priority == 1 %}
	<span class="badge bg-gradient-info">Low</span>
{% endif %}

templates/includes/task_status_indicator.html
{% if task.is_completed %}
	<span class="text-gradient text-success fw-bold">Resolved
		<i class="fas fa-check-circle"></i></span>
{% else %}
	<span class="text-info  fw-bold">In
		progress <i class="fas fa-spinner"></i>
	</span>
{% endif %}